### ISSUE TITLE
Not an issue. Just wanted to appreciate 

### ISSUE THREAD

**Issue by JerryI** [fuermosi777/markword#1]
Great project, I did help me a lot with making syntax sugar for my project. ❤️
This is the best example for using Decorations from CM6 I  have seen so far.

**Comment by fuermosi777** [comment]
Thank you and glad this helps.

**Comment by JerryI** [comment]
I would actually recommend to make an npm package, since this is the only extension for Markdown that allows to see the live preview. For the community it could very useful.
